[package]
name = "mediaplayer"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc.0", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.16", features = [ "tray-icon", "protocol-asset"] }
tauri-plugin-single-instance = "2.0.0-rc.4"
tauri-plugin-fs = "2.0.0-rc.5"
tauri-plugin-dialog = "2.0.0-rc.7"
tauri-plugin-clipboard-manager = "2.0.0-rc.4"
tauri-plugin-shell = "2.0.0-rc.3"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
webview2-com = "0.33"
once_cell = "1.19.0"
async-std = "=1.13.0"
win32props = { git = "https://github.com/mrdkprj/r_win32props.git" }

[dependencies.wcpopup]
version = "0.3.1"
#features = ["accelerator"]

[dependencies.windows]
version = "0.58"
features = [
    "Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader"
]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[patch.crates-io]
tao = { path = "./tao-0.29.0" }
#wry = { path = './wry-0.39.1' }
#webview2-com-sys = { path = './webview2-com-sys-0.28.0' }
wcpopup = { path = "../../wcpopup" }
