[package]
name = "taltmediaplayer"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.2.5", features = [ "tray-icon", "protocol-asset", "devtools"] }
tauri-plugin-single-instance = "2.0.0"
tauri-plugin-shell = "2.2.0"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19.0"
async-std = "1.13.0"
nonstd = { git = "https://github.com/mrdkprj/movefile.git", rev="57e58fbb0c9eeb1a37362d2069f5ab1df2192672" }

[dependencies.wcpopup]
version = "0.5.1"

[target.'cfg(target_os = "windows")'.dependencies.webview2-com]
version = "0.34"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58"
features = [
    "Foundation",
]

[target.'cfg(target_os = "linux")'.dependencies.gtk]
version = "0.18.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[patch.crates-io]
#tao = { path = "./tao-0.29.0" }

