[package]
name = "mediaplayer"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [ "tray-icon", "protocol-asset"] }
tauri-plugin-single-instance = "2.0.0"
tauri-plugin-fs = "2.0.0"
tauri-plugin-dialog = "2.0.0"
tauri-plugin-clipboard-manager = "2.0.0"
tauri-plugin-shell = "2.0.0"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19.0"
async-std = "1.13.0"

[dependencies.wcpopup]
version = "0.3.4"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[patch.crates-io]
#tao = { path = "./tao-0.29.0" }
#wry = { path = './wry-0.39.1' }
#webview2-com-sys = { path = './webview2-com-sys-0.28.0' }
#wcpopup = { path = "./wcpopup" }
